# Generated by Django 3.2.15 on 2022-10-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='full_name',
        ),
        migrations.AddField(
            model_name='reporter',
            name='firstname',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='reporter',
            name='lastname',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
