# Generated by Django 3.2.15 on 2022-10-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_auto_20221027_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
    ]
