# Generated by Django 3.2.16 on 2022-12-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_auto_20221114_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='reporter',
            constraint=models.UniqueConstraint(fields=('firstname', 'lastname'), name='unique_reporter'),
        ),
    ]
